# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genremodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='genremodel',
            name='genre_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
